Update README.rst
There seems to be a missing method call and the tab completion has uppercase tickers available. `tickers.msft.info` results in `AttributeError: 'Tickers' object has no attribute 'msft'`, while `tickers.tickers.MSFT.info` works as expected.